### PR TITLE
Changed migratedresume-data.js

### PR DESCRIPTION
**Pull request by harshilparmar**
@aamay001 changed code as per you said  in #104 for #72

### CODE REVIEW

**Comment by aamay001** [comment]
There is a failing test. Can you please update the test?. [See Failing Test](https://dev.azure.com/aamay001/react-resume/_build/results?buildId=119&view=logs&j=44b61185-70a3-5078-88e3-0bc2f172e420&t=41107afb-7ef3-5972-276a-e9c5f30274b8&l=475)

**Comment by harshilparmar** [comment]
@aamay001 Can you tell me where I am going wrong!! I have also changed ``` cypress/integration/components/Tools/CodeEditor.spec.js```. 
cypressfailed

**Comment by aamay001** [comment]
> @aamay001 Can you tell me where I am going wrong!! I have also changed ` cypress/integration/components/Tools/CodeEditor.spec.js`.
> cypressfailed

This is most likely because the test command is formatted for a unix based terminal. Try entering the command directly like this:

`npx start-server-and-test "npm start" 3000 "cypress run --headed"`

**Comment by harshilparmar** [comment]
@aamay001 There are two errors.Can please guide.
cypressfailed

**Comment by aamay001** [comment]
> @aamay001 There are two errors.Can please guide.
> cypressfailed

@harshilparmar Please send me an email so I can provide secrets that are required. Thanks. (My email is on my profile.)

**Comment by aamay001** [comment]
@harshilparmar there is an issue with the CI pipeline that is preventing the tests from running successfully. I've contacted MS to get support on this and I will merge in your changes once the issue has been resolved and all tests pass successfully. In the meantime, I have added the label `hacktoberfest-accepted` to your PR. Thanks for your patience with this.

**Comment by harshilparmar** [comment]
@aamay001 It's my pleasure brother. looking forward to do more contribution.😃

**Pull request closed without merging**
