### PR TITLE
Test Cypress Code Editor

### PR DESCRIPTION
**Pull request by PhilippeBarre**
This test was not as easy as I thought it would be:
I wanted to get the whole json by default and modify the elements one by one.

But your element (.ace_content > .ace_text-layer) actually displays only the part of the json visible with the scroll and not the whole json.

So, in my test I simply replace the whole json and check that the rendering has been updated.

image

Issue : CodeEditor: Add Cypress test #85

### CODE REVIEW

**Review by aamay001 — CHANGES_REQUESTED** [review]
Can you include tests for the editor status string? 

The editor status can change from `waiting for input` to `code updated` to `invalid json`

When the status string is updated, the color of the top border on the code editor also changes. Please include that as well.

**Comment by PhilippeBarre** [comment]
All right, I'll look into it.

**Comment by PhilippeBarre** [comment]
Hello @aamay001 
I have pushed tests that check the status of code editor as well as the colour of the top border.

**Review by aamay001 — APPROVED** [review]
Thank you for your contributions!

**Pull request merged**
