### PR TITLE
Adding Icons in header for website, GitHub, LinkedIn, mail and phone.

### PR DESCRIPTION
**Pull request by ram-nad**
:sparkles: Adding `svg icons` in resume header.

### CODE REVIEW

**Comment by ram-nad** [comment]
Screenshot_20191003_152920

This is the result.

**Comment by ram-nad** [comment]
Sir, wouldn't be only one `showIcon` be sufficient.

**Comment by aamay001** [comment]
> Sir, wouldn't be only one `showIcon` be sufficient.

Yes, that works.

**Comment by aamay001** [comment]
Just FYI, a new feature was pushed that allows toggling additional settings. Please add the `showIcon` toggles for header icons in the More Visibility modal.

**Comment by ram-nad** [comment]
> Just FYI, a new feature was pushed that allows toggling additional settings. Please add the `showIcon` toggles for header icons in the More Visibility modal.

Sir but More Visibility Modal is being used for changing resume content and not its appearance. So, I feel that we should add `showIcon` button in `Visibility Changer` only.

**Comment by ram-nad** [comment]
Sir I have added `showIcon` option in visibility changer for now. I would put it in `More Visibility Modal` if you say to do so.

**Pull request merged**
