### PR TITLE
Font size adjustment

### PR DESCRIPTION
**Pull request by avinashbnaik**
I've added the functionality to adjust font size.
Please review and let me know if you have any concerns.

### CODE REVIEW

**Comment by aamay001** [comment]
@avinashbnaik,

This looks really good. Thank you for working on this! I have a few requests to make this a more complete tool. Can you add a `select` element to the left of the input for selecting the different element types that are in the resume? 

Here is a rough sample:
Font Size
[ Select: [h1, h2, h3, li] [ number input ] (two columns for tool)

Additionally, please make sure to check the JS console and clear any errors/warnings that are produced by any new code that's added. Please keep the default font size at 10px.

**Comment by avinashbnaik** [comment]
Shall i use styled-components ?
I can't think of a better way to do this,
Let me know if you have any alternatives

**Comment by aamay001** [comment]
@avinashbnaik I don’t have a preference as long as the general programming style used. You’ve already done this in your last commit. I haven’t personally used `styled-components` but it would be great to introduce it into this project.

**Comment by aamay001** [comment]
@avinashbnaik Let me know if you're still planning on doing this. Would like to have this feature.

**Comment by avinashbnaik** [comment]
@aamay001 Yes, I will implement this feature!

**Comment by aamay001** [comment]
> @aamay001 Yes, I will implement this feature!

Hi @avinashbnaik, are you still planning on completing this feature?  If not, I will close this thread.

Thanks for your contributions.

**Comment by avinashbnaik** [comment]
I'm sorry, I've been busy with other work, so i wont be able to do this anytime soon!

**Pull request closed without merging**
