### PR TITLE
EditorButton: Add Cypress Test

### PR DESCRIPTION
**Pull request by jespicas**
I created the test.
This test click on EditorButton
Check if exist label of Editor
And close the Editor and go to Home page
Screenshot from 2020-10-03 15-04-48

### CODE REVIEW

**Review by aamay001 — CHANGES_REQUESTED** [review]
Can you include an assertion at the end that checks that the Code Editor is **not** open after you have closed it?

**Comment by jespicas** [comment]
> Can you include an assertion at the end that checks that the Code Editor is **not** open after you have closed it?

I will do!

**Comment by jespicas** [comment]
Added the assert
assert

**Comment by aamay001** [comment]
> Added the assert
> assert

Thank you for adding this. There is a merge conflict. Can you please resolve it?

**Comment by jespicas** [comment]
> > Added the assert
> > assert
> 
> Thank you for adding this. There is a merge conflict. Can you please resolve it?

It's fix

**Review by aamay001 — APPROVED** [review]

**Comment by aamay001** [comment]
Thanks for your contributions.

**Pull request merged**
